# This file was generated by GoReleaser. DO NOT EDIT.
cask "cnap" do
  name "cnap"
  desc "CLI for managing CNAP workspaces, clusters, and deployments"
  homepage "https://docs.cnap.tech/cli"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cnap"
  bash_completion "completions/cnap.bash"
  zsh_completion "completions/cnap.zsh"
  fish_completion "completions/cnap.fish"

  on_macos do
    on_intel do
      url "https://github.com/cnap-tech/cli/releases/download/v#{version}/cnap_#{version}_darwin_amd64.tar.gz"
      sha256 "861ac1199b2fc49e1a690df18cbe6055e35c59795fba98796b71145edf381bda"
    end
    on_arm do
      url "https://github.com/cnap-tech/cli/releases/download/v#{version}/cnap_#{version}_darwin_arm64.tar.gz"
      sha256 "2eb1a819567c82b0a8f57a8ef04afecce8306bcf125076f735d1571aa5878bde"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cnap-tech/cli/releases/download/v#{version}/cnap_#{version}_linux_amd64.tar.gz"
      sha256 "e7d74a47b2aa1ae51891a0550c42433834eab2d03181f936ceffa7ad515f98ff"
    end
    on_arm do
      url "https://github.com/cnap-tech/cli/releases/download/v#{version}/cnap_#{version}_linux_arm64.tar.gz"
      sha256 "bc0f8cacfc35e0ae5877266a1ab1da8283ce1027e8f6948ac7adc4c76e84c7f4"
    end
  end

  # No zap stanza required
end
