# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnap < Formula
  desc "CLI for managing CNAP workspaces, clusters, and deployments"
  homepage "https://cnap.tech"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnap-tech/cli/releases/download/v0.1.0/cnap_0.1.0_darwin_amd64.tar.gz"
      sha256 "85c563b2005f697ce88c4e1b5c9bef8c20c2861873444270a5a7d44a9d335b76"

      def install
        bin.install "cnap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnap-tech/cli/releases/download/v0.1.0/cnap_0.1.0_darwin_arm64.tar.gz"
      sha256 "e03a1e7f55514b3affe14ba34dec1caadfef902e1d653cbf92353bebc4912700"

      def install
        bin.install "cnap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnap-tech/cli/releases/download/v0.1.0/cnap_0.1.0_linux_amd64.tar.gz"
      sha256 "33be55548f646b9d23ce3befcfafa6331d9f97fd63b1c91749ad6a5573548557"
      def install
        bin.install "cnap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnap-tech/cli/releases/download/v0.1.0/cnap_0.1.0_linux_arm64.tar.gz"
      sha256 "1481f0115c63fd897925336b057b92e6e2974a326cfe6386d3999d768b6dfd32"
      def install
        bin.install "cnap"
      end
    end
  end
end
