# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnap < Formula
  desc "CLI for managing CNAP workspaces, clusters, and deployments"
  homepage "https://docs.cnap.tech/cli"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnap-tech/cli/releases/download/v0.6.1/cnap_0.6.1_darwin_amd64.tar.gz"
      sha256 "3724b0b22fa9f2b88431ae34c5515fce5590b1b0950c8a4389dd03d3114dd463"

      def install
        bin.install "cnap"
        bash_completion.install "completions/cnap.bash" => "cnap"
        zsh_completion.install "completions/cnap.zsh" => "_cnap"
        fish_completion.install "completions/cnap.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnap-tech/cli/releases/download/v0.6.1/cnap_0.6.1_darwin_arm64.tar.gz"
      sha256 "0b87a594877eb7edfbb4aa6fb8ac92156c276ee7d649fb58b7d18a9fd586a812"

      def install
        bin.install "cnap"
        bash_completion.install "completions/cnap.bash" => "cnap"
        zsh_completion.install "completions/cnap.zsh" => "_cnap"
        fish_completion.install "completions/cnap.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnap-tech/cli/releases/download/v0.6.1/cnap_0.6.1_linux_amd64.tar.gz"
      sha256 "e9c8fa03958ea586944987a142c8ef060944faea11e1ded9c40cf32449f5f600"
      def install
        bin.install "cnap"
        bash_completion.install "completions/cnap.bash" => "cnap"
        zsh_completion.install "completions/cnap.zsh" => "_cnap"
        fish_completion.install "completions/cnap.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnap-tech/cli/releases/download/v0.6.1/cnap_0.6.1_linux_arm64.tar.gz"
      sha256 "a1da387b74167a71f5d4ec480ca35564841e05c715c2af2f7d99795dd1dd15f6"
      def install
        bin.install "cnap"
        bash_completion.install "completions/cnap.bash" => "cnap"
        zsh_completion.install "completions/cnap.zsh" => "_cnap"
        fish_completion.install "completions/cnap.fish"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cnap --version")
  end
end
